### ISSUE TITLE
Error when trying out the books' code samples

### ISSUE THREAD

**Issue by uzabumuhire** [naltatis/micro-frontends-in-action-code#15]
I have the following error  when executing the books' code samples using Node.js version 14.16.0 with NPM version 6.14.11 on Powershell 7.1.3  Windows 10 :

`PS C:\Users\uzabu\dev\learn\microfrontend> npm run 01_pages_links

> micro-frontends-in-action-code@1.0.0 01_pages_links C:\Users\uzabu\dev\learn\microfrontend
> concurrently --names "decide ,inspire" "mfserve --listen 3001 01_pages_links/team-decide" "mfserve --listen 3002 01_pages_links/team-inspire" "wait-on http://localhost:3001/product/porsche && opener http://localhost:3001/product/porsche"   

[decide ] Error occurred when executing command: mfserve --listen 3001 01_pages_links/team-decide
[decide ] Error: spawn cmd.exe ENOENT
[decide ]     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
[decide ]     at onErrorNT (internal/child_process.js:465:16)
[decide ]     at processTicksAndRejections (internal/process/task_queues.js:80:21)
[inspire] Error occurred when executing command: mfserve --listen 3002 01_pages_links/team-inspire
[inspire] Error: spawn cmd.exe ENOENT
[inspire]     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
[inspire]     at onErrorNT (internal/child_process.js:465:16)
[inspire]     at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2] Error occurred when executing command: wait-on http://localhost:3001/product/porsche && opener http://localhost:3001/product/porsche
[2] Error: spawn cmd.exe ENOENT
[2]     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
[2]     at onErrorNT (internal/child_process.js:465:16)
[2]     at processTicksAndRejections (internal/process/task_queues.js:80:21)
[2] wait-on http://localhost:3001/product/porsche && opener http://localhost:3001/product/porsche exited with code -4058
[inspire] mfserve --listen 3002 01_pages_links/team-inspire exited with code -4058
[decide ] mfserve --listen 3001 01_pages_links/team-decide exited with code -4058
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! micro-frontends-in-action-code@1.0.0 01_pages_links: `concurrently --names "decide ,inspire" "mfserve --listen 3001 01_pages_links/team-decide" "mfserve --listen 3002 01_pages_links/team-inspire" "wait-on http://localhost:3001/product/porsche && opener http://localhost:3001/product/porsche"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the micro-frontends-in-action-code@1.0.0 01_pages_links script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\uzabu\AppData\Roaming\npm-cache\_logs\2021-04-27T07_42_34_137Z-debug.log`

**Comment by naltatis** [comment]
Hi @uzabumuhire,  I've update the `concurrently` dependency. The previous version had a similar error (https://github.com/kimmobrunfeldt/concurrently/issues/232) that your report. Can you check if this works for you now.

**Comment by uzabumuhire** [comment]
After pulling your updates, I was still having the same issue after some search on the internet I was able to resolve the issue by adding  **C:\Windows\System32** to the **System PATH environment variable** (Source : https://stackoverflow.com/questions/57054403/problem-with-npm-start-error-spawn-cmd-enoent)

**Comment by naltatis** [comment]
Glad that it works. Thanks for the info @uzabumuhire

**Comment by uzabumuhire** [comment]
@naltatis,  thanks a lot for taking your time to help me.
