### ISSUE TITLE
Please stop propagating the micro-frontends approach.

### ISSUE THREAD

**Issue by padcom** [naltatis/micro-frontends-in-action-code#16]
Yes, I know how that sounds.

The idea of splitting a codebase into smaller chunks isn't new. I think we can all agree on that. It originated way back in the desktop world where things like dynamically loaded libraries (be that .so, .dll, .jar or what have you) allow for sharing parts of the code between different projects but also allow parts of a single application to be developed independently (to a degree where the API still matches the user and the library). Please note that in all those cases, we're still talking about a single process which matches the way web applications are done.

That can be achieved, although not easily, with npm packages that can be separately deployed to the registry and then linked as a single application that runs in the single-process and single-threaded environment that the browser is. Of course there are separate threads that are being spawn by the browser itsel, but to the user (as in the developer) for all intent and purposes the environment is single threaded and single process.

In contrast, the idea of micro-services is very much different. Although living with just a single thread per process isn't all that unthinkable (if the platform you're running your code deals with it like e.g. node.js does) but running multiple processes inside the browser is just not doable in a performant way. The one and only way to simulate the microservices architecture in the browser is by using iframes. That's a fact.

Following what people think about micro-frontends and what has been proposed is very much different.

First of all, you don't want to have code duplication. Duplicating code makes the app load slower. We don't want that, because it will make our page/app rank lower. We definitely don't want that. This eliminates things like multiple copies of that same library.

Secondly, the idea of having the ability to deploy (we'll get to that what it means in just a second) separately is very tempting. After all, who wouldn't like to be able to deploy part of the system so that the rest of it is oblivious to the change, right? Well, the only problem is that you're not deploying anything at any time other than when the browser requests the resources and runs them. That is where the rubber meets the road. And so any and all ideas that you "deploy to npm registry" or "deploy to server" means absolutely nothing because that is no deployment whatsoever. That's just copying bytes around. They do nothing on the server.

To that end, any mirage of server-side includes and frontend code that stems from it is just the wrong thing to do. Instead of even thinking how to marry the two worlds together, it is much more beneficial to organize the system in a more homogeneous way so that it is not only easier to develop but also to maintain.

In the end it is just the wrong thing to do with all the server-side includes and web components (which nobody uses besides google). Today's FE world runs on frameworks (Vue.js, Angular, React). All of those frameworks are HUGE. Doing what has been proposed, that every team has a certain degree of freedom in choosing their own tool of choice is just not going to fly. Even in the microservices peope tend to standardize on a single language and framework because that way it is far easier to find developer replacement in this world where a typical timespan over which a developer works for a single project (or company) is about 6 months.

To bottom line this it is my humble request that you stop promoting this solution that (as time has shown) only works in hardly-working examples, all of which violate the primary rule of what architecture should provide: ease of development and maintenance. This is the take-away from my 5 years with the idea, trying to implement it in real-world scenarios. Not a single one has led to better DX nor to faster load times.

Working with FE is hard enough. Don't make it harder for no reason, selling dreams that never come true.

**Comment by naltatis** [comment]
Hi @padcom, I'm sorry to hear that this paradigm hasn't been working for your projects. We have very positive experiences in the projects we've been working on. I also see more and more companies successfully adopting this pattern. In all of our  projects, micro frontends provided the ability to work independently with more people on it and we indeed see the business benefits of being able to iterate faster and regaining the feel of ownership. That said, I would never propose micro frontends to being the silver bullet or the one and only frontend architecture. Having the organizational and business goals align with the architecture is a key factor of success in our experience. 

Regarding "using huge frameworks" and "standardization": I'm a big fan of using smaller libraries, I've you've read the book this repository belongs to or have seen one of my talks you might have notices that. I'm also not advocating to mix and match different heavy libraries without having a really good reason for it. But, especially for large projects, I see the value in not limiting the complete organisation / web property to one specific version of a frontend framework.

As you wrote in this issue, you have had different experiences with this technique and I won't try to change your opinion on this. But saying that this is an architecture that's inherently to complicated and doesn't bring any real benefits is not true. So I hope we can agree to disagree :D

Thanks for reaching out!

**Comment by padcom** [comment]
Would you mind sharing which libraries would you consider using? I am curious what is "small" in your mind. 

And thanks for the reply!

**Comment by naltatis** [comment]
The library question is dependent on the use-case and it's performance requirements.

We've built e-commerce websites with all teams using a React based stack. 

I'm currently working on a back office system where startup performance is not so critical (behind a login), there all teams use Vue, except one team that uses Svelte because they already had existing code that shouldn't be rewritten.

I'd classify React and Vue as "big" libraries. In these projects we established a technical mechanism to not redownload react/vue multiple times and encouraged all teams to upgrade in a given timeframe to not have different versions of those libraries at the same time.

In another project we opted for a light stack. Teams could choose their library freely but had it had to support JSX component and not large runtime. There we ended up with Preact and Hyperapp systems. Since both libraries are very small we didn't have the need (and complexity) to provide central library versions at all.

Here's a slide where I talked about vendor library footprint: https://speakerdeck.com/naltatis/bye-bye-frontend-monolith-accelerating-feature-development-with-micro-frontends?slide=59

**Comment by padcom** [comment]
@naltatis You might want to check out https://www.npmjs.com/package/@padcom/npm-serve. I've made it specifically to not be forced to use any bundlers or custom elements. An example project that uses it can be found in https://github.com/padcom/importmap-vue3-react-mf-example repository. Basically just cd to host and npx @padcom/npm-serve and you're all set.

**Comment by padcom** [comment]
In my humble opinion the idea of splitting the application into smaller, separately deployable pieces is good. Just the mechanism of custom elements doesn't seem to solve all the issues (like deployment, runtime composition, multiple frameworks etc). With `importmap` all of that is perfectly possible. I feel that it just isn't the right level of abstraction that is needed for the idea to be useful.
