### ISSUE TITLE
Provide link to sources on manning.com

### ISSUE THREAD

**Issue by padcom** [naltatis/micro-frontends-in-action-code#17]
https://www.manning.com/books/micro-frontends-in-action

Look for resources and try to download the source code...

**Comment by naltatis** [comment]
The GitHub link is available behind the "show all" link
![Bildschirmfoto 2022-01-13 um 18 30 35](https://user-images.githubusercontent.com/152287/149379857-3b54f97d-5b80-40b0-a776-bb1975d4d5d4.png)
.
